### ISSUE TITLE
RDML file compression / XML naming

### ISSUE THREAD

**Issue by dwightkuo** [RDML-consortium/rdmlpython#3]
This is a minor issue, but BioRad RDML files outputted by CFX Maestro do not conform to the RDML standard as they have variable names / directory structures whereas the standard requires that the xml file has the name "rdml_data.xml". This makes linregpcr fail when directly inputting the rdml file. The workaround is to unzip the rdml and directly use the xml file as the input, but can this filename restriction be loosened in rdmlpython so that it can accept rdml files where the internal xml has a different name?

**Comment by untergasser** [comment]
I know, I know...

And I created the function load_any_zip(filename) for this :-)

Best,

Andreas

**Comment by bhughes339** [comment]
Hi @untergasser, thank you for adding that feature. Would it be possible to push the most recent version to `pip` so I can install it without downloading from source? Thank you!

**Comment by untergasser** [comment]
I just updated it. I have to update it more frequently :-)

Best,
Andreas
