### ISSUE TITLE
Which Cq and efficiency values to use for absolute quantification?

### ISSUE THREAD

**Issue by EA-French** [RDML-consortium/rdmlpython#5]
Hello,
I am trying to write a script to calculate copy number based on the absolute quantification method from Ruijter et al 2021 (Eq 11), using the PCR efficiency on a by-sample basis as I see different qPCR efficiencies between samples. So far, I have calculated the average PCR efficiency by sample (from the indiv PCR eff column) and the average efficiency of my standard known copy number samples. However, I'm stuck trying to figure out which calculated Cq value I should use in the calculation since there are multiple Cqs calculated different ways, and I don't fully understand the differences between them. I would assume using the Cq calculated with the mean efficiency defeats the purpose of accounting for differences in amplification efficiency across samples? But I'm also not sure where the efficiency comes into the calculation of the Cq value itself? Since there's about a half Cq difference between some of the different columns, I want to make sure I'm using the correct value to make the calculation. I tried using the web browser as well, and it outputted only the "Cq (mean eff) - no plateau - stat efficiency". Is that the correct one to use? (I'm keeping the samples with no plateau). 

Example output below: 

[test_rdmlpython.csv](https://github.com/RDML-consortium/rdmlpython/files/8709569/test_rdmlpython.csv)

**Comment by untergasser** [comment]
You should use N0 for this, as it is already quantity.
The Cq is error prone and should not be used, especially as the answer to your questions depend on your experiment and its aims.

Best,

Andreas
