### ISSUE TITLE
Is there any way to display negative values using lin reg

### ISSUE THREAD

**Issue by sai7842** [RDML-consortium/rdmlpython#6]

**Comment by untergasser** [comment]
Yes, add a constant value to get all values positive - that is what the current version does. As we can not calculate logarithms from negative values, it is not possible to work with negative values...

**Comment by sai7842** [comment]
Thank you for the comment and is there any way to correct hook effect using linreg?
Please let me know.

**Comment by untergasser** [comment]
I don't think so. Why does your data have his effect and where does it come from?

Best,

Andreas
